baseURL: 'https://llmreadinggroup.github.io'
languageCode: 'en-us'
title: 'LLM Reading Group'
theme: 'hugo-tufte'

params:
  # Subtitle of the website
  subtitle: "Notes from weekly discussions"
  favicon: "./favicon.ico"
  touchicon: "./touch-icon.png"
  # Dark code highlighting
  codeblocksdark: false
  # Customize the indicator for margin notes
  # Some suggestions: âŠ•, ğŸ’¬, ğŸ’­, ğŸ“‘, ğŸ· , âœ , ğŸ’¡, ğŸ§, ğŸ“, ğŸ“Œ
  marginNoteInd: "âŠ•"
  # Your name or the name of you company
  # copyright: Copyright 2023
  # copyrightHolder: Copyright Holder
  # Show the "Powered by Hugo-Tufte and Hugo."
  showPoweredBy: false
  # Site wide kill switch for date in pages
  hidedate: false
  # Site wide kill switch for post summary on home page
  showSummary: true
  # Site wide kill switch for LaTeX support
  math: true
  KaTeXVersion: 0.16.4
  KaTeXCDN: "//cdn.jsdelivr.net/npm"
  # Common social website links, please comment the unused ones.
  # (if your favorite one is not in the list, please head to the footer menu below and add an entry)
  # Please note that some of the value below are only provided as an exemple, perhaps the computed isn't valid
  # github: slashformotion
  # gitlab: slashformotion
  # twitter: slashformotion
  # patreon: ''
  # youtube: user/ChromeDevelopers # check the end of your youtube url https://www.youtube.com/<copy_this>
  # medium: slashformotion
  # reddit: Slashformotion
  # stackoverflow: 16609732/slashformotion
  # instagram: google
  # mastodon: instance.url/@username
  # orcid: 0000-0003-0634-3275
  # google_scholar: jm5QaHkAAAAJ

menu:
  nav:
    - name: Home
      weight: -110
      identifier: home
      url: /
    - name: Posts
      weight: -100
      identifier: posts
      url: /posts/
    - name: Github
      weight: -70
      identifier: github
      url: "https://github.com/llmreadinggroup/llmreadinggroup.github.io"
    - name: About
      weight: -80
      identifier: about
      url: /about/

# Enable Hugo renderer to allow raw HTML in markdown
markup:
  goldmark:
    renderer:
      unsafe: true
